language:
- generic
dist: trusty
sudo: true
addons:
  apt:
    packages:
    - texlive-latex-extra
    - texlive-luatex
    - cm-super
    - texlive-bibtex-extra
    - latexmk
    - tex4ht
    - biber
    - texlive-fonts-recommended
    - texlive-lang-italian
    - latex-xcolor
    - texlive-publishers
    - pgf
    - R
    - perl
    - openjdk-7-jdk
    - openjdk-7-jre
script:
- make
before_deploy:
- git fetch --tags
#deploy:
#  provider: releases
#  file: GhioCA.pdf
#  skip_cleanup: true
#  on:
#    repo: Augugrumi/GhioCA-Paper
#    tags: true
